In [1]:
import pandas as pd
import numpy as np
import random

In [27]:
directory = "/static/data/"
crime_df = pd.read_csv("crime_cleaned_data.csv")
avg_temp_df = pd.read_csv("daily_avg_temps.csv")
max_temp_df = pd.read_csv("daily_max_temps.csv")
min_temp_df = pd.read_csv("daily_min_temps.csv")
avg_humidity_df = pd.read_csv("daily_2015_avg_humidity.csv")
max_humidity_df = pd.read_csv("daily_2015_max_humidity.csv")
min_humidity_df = pd.read_csv("daily_2015_min_humidity.csv")
avg_wind_df = pd.read_csv("daily_2015_avg_wind.csv")
max_wind_df = pd.read_csv("daily_2015_max_wind.csv")
min_wind_df = pd.read_csv("daily_2015_min_wind.csv")

In [28]:
def time_warp(df):
    # Takes in a pandas DataFrame, splits a YYYY-MM-DD format datetime column into a Year, Month, and Day column while retaining the original column for later use
    df['Year']=[d.split('-')[0] for d in df.datetime]
    df['Month']=[d.split('-')[1] for d in df.datetime]
    df['Day']=[d.split('-')[2] for d in df.datetime]
    return df

In [29]:
df = time_warp(avg_temp_df)

In [31]:
df[(df["Year"] == "2015")]

,datetime,Vancouver,Portland,San Francisco,Seattle,Los Angeles,San Diego,Las Vegas,Phoenix,Albuquerque,...,Miami,Pittsburgh,Toronto,Philadelphia,New York,Montreal,Boston,Year,Month,Day
822,2015-01-01,33.04,22.33,47.33,28.21,34.58,32.12,31.12,31.88,15.50,...,74.75,24.79,23.25,25.42,24.46,19.08,25.92,2015,01,01
823,2015-01-02,35.58,24.50,42.92,30.33,33.75,33.58,22.92,30.54,18.00,...,74.96,30.62,28.17,33.83,33.67,22.12,34.54,2015,01,02
824,2015-01-03,36.38,32.83,43.92,36.88,35.58,35.42,25.00,31.17,19.62,...,76.88,32.08,26.29,28.62,27.71,6.92,28.33,2015,01,03
825,2015-01-04,37.88,38.58,45.25,37.04,41.21,38.12,26.96,34.83,22.54,...,77.12,53.08,38.17,49.79,41.00,20.62,44.08,2015,01,04
826,2015-01-05,40.17,46.96,46.33,50.42,41.50,44.50,30.04,41.42,21.88,...,75.88,25.71,21.71,37.58,39.58,14.79,39.88,2015,01,05
827,2015-01-06,44.67,41.00,49.25,47.71,46.58,49.42,35.42,45.46,27.00,...,76.08,16.12,13.71,20.71,20.67,0.17,19.58,2015,01,06
828,2015-01-07,42.29,35.96,51.54,41.21,49.75,50.88,39.79,49.04,29.17,...,73.83,14.96,10.50,19.21,17.75,5.46,19.00,2015,01,07
829,2015-01-08,42.04,33.54,51.75,40.46,57.38,52.88,40.58,58.58,23.17,...,65.33,8.79,11.96,13.88,12.38,-9.46,12.96,2015,01,08
830,2015-01-09,41.88,34.58,53.17,40.46,56.67,54.62,39.83,49.50,25.88,...,68.38,19.29,19.04,22.58,21.58,13.42,25.67,2015,01,09
831,2015-01-10,41.75,32.33,51.79,40.17,50.04,51.21,44.33,53.38,26.08,...,68.88,8.00,13.96,16.54,15.79,10.08,21.79,2015,01,10
832,2015-01-11,43.08,39.62,52.25,42.83,53.33,54.12,43.75,49.58,30.08,...,72.67,16.75,18.58,15.75,15.42,14.88,20.33,2015,01,11
833,2015-01-12,43.42,39.42,51.04,44.33,47.79,51.96,46.42,54.92,31.83,...,73.42,34.58,26.58,29.88,27.71,23.25,34.08,2015,01,12
834,2015-01-13,42.12,36.54,52.38,39.33,45.29,49.92,41.17,52.08,32.29,...,72.08,23.71,6.79,29.33,27.25,1.83,27.96,2015,01,13
835,2015-01-14,42.08,34.33,50.17,37.21,47.17,48.54,43.25,45.83,32.25,...,70.29,21.62,10.83,19.50,17.04,-4.21,23.42,2015,01,14
836,2015-01-15,41.25,33.25,49.33,35.29,43.71,47.38,35.12,46.08,27.25,...,70.62,20.54,11.50,22.67,20.25,-0.83,28.50,2015,01,15
837,2015-01-16,45.29,45.75,51.92,46.04,46.17,47.17,33.33,47.04,24.71,...,67.50,25.88,21.71,25.04,24.62,15.96,27.33,2015,01,16
838,2015-01-17,43.96,40.67,51.79,38.42,49.75,49.67,36.50,45.96,27.75,...,65.46,26.54,13.42,18.75,17.58,-2.33,17.83,2015,01,17
839,2015-01-18,45.54,49.54,53.79,48.33,55.29,49.58,39.88,47.67,27.08,...,67.88,41.79,37.46,28.42,26.42,13.67,34.92,2015,01,18
840,2015-01-19,45.29,45.12,55.71,45.62,54.46,50.00,41.58,50.62,30.25,...,63.58,34.12,26.92,33.17,33.62,29.54,42.17,2015,01,19
841,2015-01-20,43.25,36.54,51.04,42.25,53.25,50.04,39.58,49.33,33.79,...,67.29,28.83,14.75,31.62,27.96,6.67,32.79,2015,01,20
842,2015-01-21,41.75,34.50,49.46,38.21,47.29,47.71,42.92,54.58,33.33,...,68.58,28.96,13.42,24.62,22.67,4.83,27.25,2015,01,21
843,2015-01-22,42.38,36.67,49.67,41.25,46.25,47.33,37.08,50.54,28.71,...,72.62,30.12,19.42,28.58,27.04,6.75,32.71,2015,01,22
844,2015-01-23,44.75,40.88,48.71,45.54,46.92,47.46,35.75,46.25,19.83,...,73.12,26.75,26.17,25.04,24.79,17.38,28.75,2015,01,23
845,2015-01-24,47.21,48.71,53.50,52.83,59.17,48.17,44.17,49.42,21.21,...,73.04,31.29,26.71,32.50,30.04,29.50,32.33,2015,01,24
846,2015-01-25,47.96,46.33,52.75,51.00,56.50,52.08,47.96,50.38,24.17,...,59.42,34.21,21.42,32.75,31.21,17.58,33.54,2015,01,25
847,2015-01-26,46.25,42.71,51.50,46.96,58.21,54.96,45.25,51.25,27.58,...,59.75,33.83,14.58,27.75,22.58,1.21,24.17,2015,01,26
848,2015-01-27,46.54,43.12,54.12,49.58,54.88,54.00,50.58,57.04,31.21,...,58.75,23.71,15.67,26.12,24.96,8.42,27.75,2015,01,27
849,2015-01-28,45.33,47.38,53.67,46.88,49.62,52.21,42.79,53.12,36.33,...,58.71,18.58,14.54,22.17,20.29,12.29,23.17,2015,01,28
850,2015-01-29,44.29,44.00,52.62,43.12,55.17,57.25,46.04,56.79,36.75,...,61.38,23.25,24.04,18.04,14.50,9.79,24.29,2015,01,29
851,2015-01-30,44.00,37.25,52.42,40.83,54.88,57.79,47.04,56.21,35.50,...,64.75,27.25,20.25,30.17,28.96,21.79,33.00,2015,01,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,2015-12-02,41.71,36.50,49.42,42.88,57.25,56.21,41.21,47.33,33.67,...,77.58,48.58,42.38,52.04,47.75,36.42,41.79,2015,12,02
1158,2015-12-03,47.75,40.00,50.12,48.25,60.29,60.08,43.79,52.42,35.54,...,76.42,36.88,38.29,48.38,49.12,37.75,47.08,2015,12,03
1159,2015-12-04,43.79,46.33,50.79,47.67,56.04,56.21,44.88,54.79,35.75,...,72.67,38.42,40.71,43.04,44.92,36.17,40.58,2015,12,04
1160,2015-12-05,44.62,44.62,47.04,46.17,55.67,56.67,45.08,54.38,40.79,...,74.17,32.62,39.08,38.04,40.54,40.54,39.88,2015,12,05
1161,2015-12-06,45.71,48.17,51.67,48.71,60.88,60.17,44.88,55.46,37.33,...,76.62,33.79,34.79,36.58,39.33,38.00,39.79,2015,12,06
1162,2015-12-07,45.62,50.67,56.17,49.71,60.58,59.50,44.46,59.83,36.25,...,74.50,35.46,36.00,39.92,41.75,35.21,42.17,2015,12,07
1163,2015-12-08,46.54,58.29,54.67,52.67,63.17,60.54,48.08,55.92,38.00,...,69.96,35.96,39.38,41.29,42.67,34.71,41.04,2015,12,08
1164,2015-12-09,45.50,55.62,56.54,51.96,63.00,60.50,49.58,55.67,44.29,...,73.75,40.88,43.29,39.00,40.62,35.38,39.08,2015,12,09
1165,2015-12-10,43.54,48.79,59.62,47.42,58.88,58.29,47.79,56.08,42.38,...,73.62,48.67,45.96,50.83,51.88,42.17,47.75,2015,12,10
1166,2015-12-11,42.04,45.00,52.58,43.62,58.50,59.79,58.17,58.04,48.62,...,74.71,52.00,49.96,47.50,48.92,46.29,48.12,2015,12,11
1167,2015-12-12,37.58,43.79,51.25,43.46,53.50,52.75,46.12,53.17,44.46,...,76.08,57.62,41.75,53.54,53.50,46.71,49.92,2015,12,12
1168,2015-12-13,42.71,45.42,55.08,45.33,53.92,52.96,43.54,45.92,32.71,...,77.08,60.92,43.50,58.38,56.29,35.21,49.12,2015,12,13
1169,2015-12-14,40.62,41.04,48.83,41.71,53.21,57.04,48.54,47.42,29.83,...,78.04,56.71,47.62,58.08,55.12,34.71,47.25,2015,12,14
1170,2015-12-15,36.96,38.33,47.62,35.79,48.21,49.17,41.08,42.33,31.08,...,76.75,48.71,47.21,59.33,59.88,37.75,53.54,2015,12,15
1171,2015-12-16,36.58,41.54,44.67,41.00,49.71,49.54,39.29,41.00,26.12,...,76.71,45.75,36.25,49.25,49.12,32.92,43.21,2015,12,16
1172,2015-12-17,33.33,41.38,45.83,37.92,49.46,49.92,35.88,41.21,25.50,...,78.50,50.08,43.96,49.46,51.17,36.42,41.25,2015,12,17
1173,2015-12-18,36.08,46.75,49.00,42.88,53.67,53.17,39.08,46.04,28.79,...,78.29,32.75,35.83,47.33,49.08,39.71,46.54,2015,12,18
1174,2015-12-19,38.38,42.17,51.00,40.62,52.46,53.21,41.08,50.79,32.83,...,71.21,28.33,28.79,35.58,36.54,32.75,36.58,2015,12,19
1175,2015-12-20,43.17,43.46,44.79,43.33,50.25,55.88,46.92,51.92,36.75,...,73.00,28.71,31.54,33.79,37.46,25.67,33.96,2015,12,20
1176,2015-12-21,39.21,43.62,51.96,39.83,48.92,50.38,41.58,49.29,33.29,...,76.58,42.96,41.58,39.38,40.92,34.12,38.58,2015,12,21
1177,2015-12-22,36.58,41.46,57.38,39.46,55.42,56.88,48.58,47.50,34.33,...,78.46,54.58,48.17,54.46,53.12,38.62,51.29,2015,12,22
1178,2015-12-23,36.58,39.75,51.67,39.21,55.75,58.75,48.00,54.08,36.79,...,78.83,53.79,45.75,56.38,51.92,38.46,49.96,2015,12,23
1179,2015-12-24,36.83,37.50,48.54,38.21,51.38,54.79,47.29,55.79,33.21,...,79.62,59.75,53.67,66.33,63.38,52.96,55.58,2015,12,24
1180,2015-12-25,35.00,37.00,43.50,37.58,49.42,53.71,44.75,52.62,36.46,...,79.25,50.67,43.83,62.46,57.04,44.00,55.12,2015,12,25
1181,2015-12-26,32.62,35.83,43.96,35.50,48.67,48.54,40.21,44.92,27.12,...,78.62,49.92,34.92,54.88,52.75,34.21,48.08,2015,12,26
1182,2015-12-27,35.75,35.83,40.29,36.83,48.38,48.62,36.42,46.29,22.12,...,78.92,56.08,36.92,53.04,51.00,31.92,45.62,2015,12,27
1183,2015-12-28,35.17,35.46,43.46,37.12,44.92,45.96,35.21,43.71,21.21,...,79.00,36.83,25.88,42.96,42.42,18.71,34.79,2015,12,28
1184,2015-12-29,34.79,37.25,42.08,37.50,45.75,47.46,38.25,44.29,22.92,...,80.04,46.17,32.92,43.33,37.62,15.38,30.75,2015,12,29
1185,2015-12-30,30.46,34.88,41.67,33.33,46.88,47.46,35.58,42.08,21.21,...,79.42,43.67,36.71,45.46,40.00,18.50,27.62,2015,12,30
1186,2015-12-31,27.38,34.46,42.58,31.42,49.42,49.50,37.54,43.42,21.88,...,79.08,37.25,34.17,46.92,44.88,26.71,36.38,2015,12,31

In [8]:
df = avg_temp_df[["Vancouver", "datetime"]][(avg_temp_df["Year"] == "2015") & (avg_temp_df["Month"] == "04")]
df = df.to_dict("list")
df2 = avg_humidity_df[["Vancouver", "datetime"]][(avg_humidity_df["Year"] == "2015") & (avg_humidity_df["Month"] == "04")]
df2 = df2.to_dict("list")

In [ ]:
var trace1 = {
  x: [1, 2, 3, 4, 5],
  y: [1, 6, 3, 6, 1],
  mode: 'markers',
  type: 'scatter',
  name: 'Team A',
  text: ['A-1', 'A-2', 'A-3', 'A-4', 'A-5'],
  marker: { size: 12 }

In [10]:
trace = {
    'x': df['Vancouver'],
    'y': df2['Vancouver'],
    'type': 'scatter',
    'name': 'Vancouver Average Temperature vs Vancouver Average Humidity',
    'mode': 'markers',
    'marker': {'size': 12,
               'symobl': 'star',
               'color': 'purple'},
    'text': df['datetime']
}
trace

{'marker': {'color': 'purple', 'size': 12, 'symobl': 'star'},
 'mode': 'markers',
 'name': 'Vancouver Average Temperature vs Vancouver Average Humidity',
 'text': ['2015-04-01',
  '2015-04-02',
  '2015-04-03',
  '2015-04-04',
  '2015-04-05',
  '2015-04-06',
  '2015-04-07',
  '2015-04-08',
  '2015-04-09',
  '2015-04-10',
  '2015-04-11',
  '2015-04-12',
  '2015-04-13',
  '2015-04-14',
  '2015-04-15',
  '2015-04-16',
  '2015-04-17',
  '2015-04-18',
  '2015-04-19',
  '2015-04-20',
  '2015-04-21',
  '2015-04-22',
  '2015-04-23',
  '2015-04-24',
  '2015-04-25',
  '2015-04-26',
  '2015-04-27',
  '2015-04-28',
  '2015-04-29',
  '2015-04-30'],
 'type': 'scatter',
 'x': [45.67,
  42.92,
  43.71,
  41.12,
  41.33,
  44.29,
  44.33,
  45.58,
  46.12,
  46.75,
  43.5,
  41.83,
  41.83,
  43.29,
  42.83,
  43.83,
  48.33,
  50.21,
  51.12,
  53.04,
  52.25,
  48.38,
  47.25,
  44.79,
  45.96,
  49.04,
  49.96,
  53.17,
  49.83,
  49.96],
 'y': [-309.75,
  -294.54,
  -294.58,
  -282.58,
  -294.38,
  -309.38,
  -305.92,
  -310.88,
  -311.67,
  -308.42,
  -282.5,
  -283.92,
  -281.75,
  -289.17,
  -304.58,
  -306.79,
  -313.21,
  -317.33,
  -317.54,
  -319.79,
  -305.17,
  -281.79,
  -280.92,
  -280.0,
  -280.12,
  -281.08,
  -281.71,
  -293.21,
  -283.12,
  -280.58]}

In [ ]:
city_json

In [11]:
def time_warp(df):
    df['Year']=[d.split('-')[0] for d in df.datetime]
    df['Month']=[d.split('-')[1] for d in df.datetime]
    df['Day']=[d.split('-')[2] for d in df.datetime]
    return df

In [43]:
# Corey's code
def create_color_codes(weather_list):
    '''
    dynamically create color codes from weather descriptions
    '''
    color_codes = []
    snow_counter = 0
    storm_counter = 0
    rain_counter = 0
    clear_counter = 0
    for value in weather_list:
        try:
            if 'snow' in value:
                color_codes.append("rgb(159,255,203)")
                if snow_counter > 1:
                    color_codes.append(f"rgb(159,255,{203 + snow_counter * 2})")
                snow_counter += 1
            elif 'storm' in value:
                color_codes.append("rgb(16,79,85)")
                if storm_counter > 1:
                    color_codes.append(f"rgb({16 + storm_counter},{79 + snow_counter},85)")
                storm_counter += 1

            elif 'rain' in value:
                color_codes.append("rgb(160,210,219)")
                if rain_counter > 1:
                    color_codes.append(f"rgb(160,{210 - rain_counter * 4},219)")
                rain_counter += 1

            elif 'clear' in value:
                color_codes.append("rgb(251,237,99)")
                if clear_counter > 1:
                    color_codes.append(f"rgb(251,237,{99 + clear_counter})")
                clear_counter += 1
            else:
                color_codes.append(f"rgb({random.randint(1,150)},{random.randint(1,50)},99)")
            
        except:
            print('nan')
    return color_codes

In [22]:
def get_descriptions(arrival, city):
    import json
    '''
    takes in a date and city and gives a json string of 
    the value counts of the weather descriptions for that month
    result json also includes dynamically changing color codes
    
    arrival: datetime as a string, 
    city: column that corresponds to the weather_description.csv
    '''
    
    df = pd.read_csv('weather_description.csv',
                     parse_dates=['datetime'], index_col='datetime')
    time_frame = df.loc[pd.date_range(arrival, periods=30, freq='D').values, :]
    weather_descriptions = time_frame[city].value_counts(ascending=False)
    #results = weather_descriptions.to_json(orient='split')
   # print(weather_descriptions.to_json(orient='split'))
    # create color codes
    color_codes= create_color_codes(weather_descriptions.index)
    final_json = {
        "name":str(weather_descriptions.name),
        "index":[x for x in weather_descriptions.index],
        "data":[int(x) for x in weather_descriptions.values],
        "color_codes": color_codes
        }
    return json.dumps(final_json)
    
get_descriptions('05/01/2015', 'Los Angeles')

clear: sky is clear
nan
nan
nan

'{"name": "Los Angeles", "index": ["sky is clear", "light rain", "scattered clouds", "broken clouds", "few clouds", "moderate rain"], "data": [12, 7, 4, 3, 2, 2], "color_codes": ["rgb(251,237,99)", "rgb(160,210,219)", "rgb(160,210,219)"]}'

In [16]:
# Set these up so the code will match in the .py file
city = 'Vancouver'
month = '05'

In [48]:
# My take on Coreys code
df = pd.read_csv('weather_description.csv')
df = time_warp(df)
df = df[[f'{city}', 'datetime']][(df['Year'] == '2015') & (df['Month'] == month)]
df = df[city].value_counts(ascending=False)
color_codes = create_color_codes(df.index)
trace = {
    'type': 'pie',
    'name': str(df.name),
    'labels': [x for x in df.index],
    'values': [int(x) for x in df.values],
    'marker': {'colors' : color_codes},
    'hole': 0.4,
    'textinfo': 'labels'
}

In [32]:
color_codes = create_color_codes(df.index)

clear: sky is clear

['rgb(251,237,99)',
 'rgb(160,210,219)',
 'rgb(122,34,99)',
 'rgb(89,49,99)',
 'rgb(64,14,99)',
 'rgb(46,6,99)',
 'rgb(160,210,219)']

In [49]:
trace

{'hole': 0.4,
 'labels': ['sky is clear',
  'light rain',
  'few clouds',
  'scattered clouds',
  'broken clouds',
  'overcast clouds',
  'heavy intensity rain'],
 'marker': {'colors': ['rgb(251,237,99)',
   'rgb(160,210,219)',
   'rgb(15,46,99)',
   'rgb(108,42,99)',
   'rgb(66,42,99)',
   'rgb(46,9,99)',
   'rgb(160,210,219)']},
 'name': 'Vancouver',
 'textinfo': 'labels',
 'type': 'pie',
 'values': [347, 121, 93, 73, 69, 40, 1]}

In [ ]:
dfs = []
for key in avg_temp_df.keys():
    print(key)
    max_df = pd.DataFrame()
    avg_df = pd.DataFrame()
    min_df = pd.DataFrame()
    max_df["city"] = [key for keys in avg_temp_df]
    min_df["city"] = [key for keys in avg_temp_df]
    avg_df["city"] = [key for keys in avg_temp_df]
    avg_df["avg_temp"] = avg_temp_df[key]
    max_df["max_temp"] = max_temp_df[key]
    min_df["min_temp"] = min_temp_df[key]
    avg_df["avg_humidity"] = avg_humidity_df[key]
    max_df["max_humidity"] = max_humidity_df[key]
    min_df["min_humidity"] = min_humidity_df[key]
    avg_df["avg_wind"] = avg_wind_df[key]
    max_df["max_wind"] = max_wind_df[key]
    min_df["min_wind"] = min_wind_df[key]
    dfs.append(avg_df)
    dfs.append(min_df)
    dfs.append(max_df)

In [ ]:
dfs.pop(0)
dfs.pop(0)
dfs.pop(0)

In [ ]:
counter = 0
for df in dfs:
    counter += 1
    if((counter + 2) % 3 == 0):
        print(df.city[0])
    print(df.corr())
    print()

In [ ]:
dfs[2]

In [21]:
airports = pd.read_csv('airport_delays.csv')
airports = airports.groupby(['DESTINATION_AIRPORT', 'MONTH', 'DAY']).sum()
airports = airports["ARRIVAL_DELAY"]

In [21]:
def csv_timeseries_data(city, month, files):
    traces = []
    i = 0
    for filename in files:
        df = pd.read_csv(directory + filename + '.csv')
        df = time_warp(df)
        df = df[[f'{city}', 'datetime']][(df['Year'] == '2015') & (df['Month'] == month)]
        df = df.to_dict('list')
        trace = {
            'x': df['datetime'],
            'y': df[city],
            'z': [i + x - x for x in range(len(df[city]))],
            'type': 'scatter',
            'name': city + ' Timeseries',
            'mode': 'lines',
            'line': {'color': color_list[i]}
        }
        traces.append(trace)
        i += 1
    return traces

In [6]:
from sqls import city_data
cities = city_data()
city_list = []
for city in cities:
    if (city['country'] == 'United States'):
        city_list.append(city['city_name'])

In [23]:
massivetracelistholyshit = []
directory = ""
month = "05"

color_list = ['#aa00aa', '#ff4444', '#4444ff']
files = ["daily_avg_temps", "daily_max_temps", "daily_min_temps"]
for city in city_list:
    massivetracelistholyshit.append(csv_timeseries_data(city, month, files))

In [11]:
import pandas as pd

In [17]:
def time_warp(df):
    # Takes in a pandas DataFrame, splits a YYYY-MM-DD format datetime column into a Year, Month, and Day column while retaining the original column for later use
    df['Year']=[d.split('-')[0] for d in df.datetime]
    df['Month']=[d.split('-')[1] for d in df.datetime]
    df['Day']=[d.split('-')[2] for d in df.datetime]
    return df